version: '3'

services:
  dqetraining2:
    image: "jenkins/jenkins"
    privileged: true
    user: admin
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "9090:9090"

  pytesttemp:
    image: "qnib/pytest"
    privileged: true
    user: admin
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "8080:8080"
